### ISSUE TITLE
`cd -` doesn't work

### ISSUE THREAD

**Issue by spinningarrow** [lunks/fish-nuggets#9] opened 2013-05-22 17:31 UTC
I followed the instructions on the [RVM website for installing rvm with fish](https://rvm.io/integration/fish/). After doing this, the `cd -` command, which normally changes the working directory to the previous directory I was in, no longer works. Instead I get this error:

```
cd: The directory '-' does not exist
```

Any idea why or how I can fix this?

**Comment by danielpclark** [comment] 2017-02-04 00:38
Can anyone verify this issue still exists? Please provide the following information if so and reopen this issue:

* Operating System & Version
* Fish-shell version
* Any aliasing or fish functions involving the command `cd`

Please also verify that without RVM added in `~/.config/fish/functions/rvm.fish` and `~/.config/fish/config.fish` that `cd -` works in the fish-shell.  _It may have been implied but was not explicitly stated._

I wasn't able to reproduce this issue with the information you have given as I've followed the same instructions and it works (`cd -` jumps to previous directory).  This may have been addressed in a fish-shell update in the years since you've opened this.

**Closed by danielpclark** 2017-02-04 00:38 UTC

**Comment by spinningarrow** [comment] 2017-02-07 15:19
@danielpclark Sorry, this is pretty ancient now. I don't use RVM any longer (or even do much Ruby development) so I don't think I can help reproduce this.
